# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0223ed6cc9b9914de5307a71c4929da8baa530a16b4e93b17ea7a95f9d0c13f108d6fcaa1d75dea918b333ccb11168049e0dae717379073f0826b364b097acd2

test:
  secret_key_base: 41888a92c7b835758b7bec30f5afface0ae156c771882453769fbd034429bcce88aeb23cef90fa3c6e5ef52feb42e227f42c03a3224b1a3b9afe51b2f5da8f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
